# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: classic-cs-problems
version: '0.0.0'
github: "chenyulue/classic-cs-problems"
license: MIT
author: "chenyulue"
maintainer: "chenyulue"
# synopsis: A new Haskeleton package.
# description: classic-cs-problems is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  classic-cs-problems:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - classic-cs-problems
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  classic-cs-problems-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - classic-cs-problems
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  classic-cs-problems-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - classic-cs-problems
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
